### ISSUE TITLE
Bug: User details do not update when editing a user

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#105]
When I tried to change the spelling of my last name from Santillian to Santillan and hit Submit on the edit modal, the modal doesn't disappear and my last name doesn't update, even though a popup appears in the lower right saying "User Created!" Also, the popup doesn't disappear either.

**Comment by nokierae** [comment]
I haven't pushed my updates to user management, so none of the forms work yet.
