### ISSUE TITLE
Bug: Since our app is often deployed offline, need an offline webfont

### ISSUE THREAD

**Issue by nokierae** [UnlockedLabs/UnlockEdv2#115]
Currently using Lato from google webfonts. Would love a hierarchy of fonts, all installed and configured locally.

**Comment by techeclecticdesign** [comment]
Has anybody started working on this? 

I am interested in doing this, but I want to clarify implementation details a little. 

I take it the goal is to not only use locally hosted fonts for Lato, but also to define globally some default styles for the various heading and p tags that currently exist using tailwind styling.  Is that correct? 

If this is the case I have two more questions. 

Where text occurs outside of a predefined heading or p tag, should Lato be used by default without opting in? 

Globals.css would be a good entry point that would reach all parts of site, or I could put style definitions into the blade templates.  Which is preferable? 

Thank you for any guidance.

**Comment by nokierae** [comment]
This was fixed.
