### ISSUE TITLE
User Modal Remains on Screen After Submitting

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#124]
Edit user modal doesn't disappear after clicking "Submit Query" and the user doesn't show up in user list until after you refresh the screen.

**Comment by nokierae** [comment]
I can't seem to reproduce this locally or on our test deployment. When I edit a user the modal closes and it refreshes in the list automatically. Where are you testing this, and if it is locally, is your branch up to date?

**Comment by chrissantillan** [comment]
@nokierae I just tested it in production instance. Created a new user named John Doe and tried to make them an Admin. The modal still didn't disappear upon submission and when I refreshed the page the role was Student. I was in a private window in firefox on the latest branch.

**Comment by nokierae** [comment]
Interesting. Being unable to set them as an admin is a known bug, but we'll have to look into the other one. I'll try to reproduce on Firefox. What OS are you on?

**Comment by Outragedpillow** [comment]
I am on Fedora Linux and experience the same issue. I am going to put in a PR today that will fix this issue

**Comment by calisio** [comment]
fixed in PR #141
