### ISSUE TITLE
Cannot Assign Admin Role to User when Creating New User

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#125]
When creating a new user, despite the fact that you can select "Admin" in the Role dropdown, the user's Role shows up as "Student" in the user list.

**Comment by nokierae** [comment]
This is duplication of #108 . It also doesn't work on editing a user. I think it has something to do with how we send over a string, but it doesn't convert into the user role enum in php, so it just defaults to 'student'
