### ISSUE TITLE
Users' table does not rerender/update when new user is added or a user is removed

### ISSUE THREAD

**Issue by Outragedpillow** [UnlockedLabs/UnlockEdv2#142]
When Adding or removing a user I noticed that the table does not rerender and have to refresh the page to see changes

**Comment by calisio** [comment]
This is probably due to not calling mutate() after success. This should be done inside of onAddUserSuccess (line 103 in Users.tsx), and should also be done after successfully deleting user!
It is part of useSWR; https://swr.vercel.app/docs/mutation
