### ISSUE TITLE
Update UI Code: Change Login.tsx and ResetPassword.tsx files to use new input components and react-hook-forms

### ISSUE THREAD

**Issue by calisio** [UnlockedLabs/UnlockEdv2#174]
We need to update the login and reset passoword pages to use the same form structure used in the rest of the application. 

**Relevant files**
Login and ResetPassword components found inside resources/js/Pages/Auth
Input components found inside resources/js/Components/inputs
Form components added into resources/js/Components/forms

**What we are looking for with this change:**
1. Login.tsx and ResetPassword.tsx should be changed to use react-hook-forms
2. New form components should be created for both login and reset password and moved to forms folder (see above)

For similar examples on how to complete this, please see the add or edit user forms that currently exist.

> Caution: There are duplicate components that are _outdated_ inside of the components folder, that will be deleted in the near future once we finish refactoring old code. **The components that should be used all live in the /inputs folder.**

**Comment by techeclecticdesign** [comment]
I would be interested in this.  I was just reading up on react-hook-forms over the last couple days, so it fits perfectly.

**Comment by calisio** [comment]
Great! Let me know if you have any questions along the way.

**Comment by techeclecticdesign** [comment]
One minor detail I would like to clarify...
If I follow the same pattern as the other form components, there will no longer be a login page, and instead there will be a login component that appears in front of the landing page.  Does that fit with what you had in mind?

**Comment by calisio** [comment]
Hi @techeclecticdesign! Your intuition about not making login a modal is correct. My thought was to just create a form component for login (ie `LoginForm.tsx`) that lives within the `/components/forms` folder, and directly using that within the `Login.tsx` page as `<LoginForm />`. So essentially you would be removing everything from lines 33 to 86 and moving them to a `LoginForm.tsx` file, and building the same form but with the input components in the `/components/inputs` folder. This is just to keep the code clean, consistent, and organized, even though its a bit less convenient since you have to create a new file.

I took a look at your code commits on your branch and it looks like you are on the right path using react-hook-forms. My one comment is that I would be aware of the additional parameters you have added to `TextInput.tsx`, as these will have to then be changed in every other file a `<TextInput />` component is used. Maybe the best way to approach this is to make a separate `PasswordTextInput.tsx` component where these values are taken in as parameters (this component can also be used in `EditProviderForm.tsx` lines 193-203, which is why I think making a separate component might be useful. Don't worry about changing `EditProviderForm.tsx` in this PR if you do end up making the `PasswordTextInput.tsx`, we can do that in a different PR). 

Which other components aren't using react-hook-forms? There are a few files that will be deleted in the near future (`Register.tsx`, `VerifyEmail.tsx`, and `ConfirmPassword.tsx`, for example), so those components will not need to be switched to react-hook-forms. Let me know if there were any other components you saw and I can take a look!

Let me know if you have any other questions that I can answer!!

**Comment by techeclecticdesign** [comment]
Hi @calisio, thank you for your reply. 

To avoid affecting existing files and requiring more boilerplate code in future parent components of TextInput, I had defined the additional parameters in TextInput to be optional and gave them reasonable defaults when they weren’t present.  I do like the idea of breaking this up into another component like you suggested, since this prevents piling more and more parameters and related code into a single ‘swiss-army knife’ component.

I may be overthinking this, but would it be best to factor common logic between TextInput and PasswordTextInput to keep things DRY?  Or should I tolerate a little code repetition to keep these independent from each other? 

As far as forms that are still handled by inertiajs, besides the three you mentioned will be deleted soon, there are four files in Pages/Profile and Pages/Profile/Partial.  Let me know if these need to be changes, please.

Thank you for your assistance.

**Comment by calisio** [comment]
Ah, I'm so sorry I didn't realize that you put those as optional (my mistake). Now that you mention that, I do think that the way you originally implemented it is okay and makes complete sense.

Yes, the files within `Pages/Profile` and `Pages/Profile/Partial` will also be deleted, so no need to worry about those!
