### ISSUE TITLE
Research: Getting activity out of Canvas

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#189]
Deliverable: What is our plan to implement this?

    How do we setup Canvas with test students and activity? (Is there a data set out there already?)

    What APIs can we pull data from in Canvas?

    What about the data we can pull if we integrate the analytics package?

    When and how often do we pull this data?

    What do our models in UnlockED look like?

Cole should have some insight. He also made some docs on Confluence. I would also ask Paul about how and what data he moved from MECC into our test environment.

- [ ] Research/Prototype LMS Data Generation Tool

**Comment by nokierae** [comment]
When Cole is done with current work, make new issues with new data extract targets.
