### ISSUE TITLE
refactor: make types explicit in all backend code

### ISSUE THREAD

**Issue by PThorpe92** [UnlockedLabs/UnlockEdv2#191]
### Currently 

```php
declare(strict_types=1);
```
was inserted via a script to all `.php` files. However, many functions, methods, classes, etc are all declared/called with dynamic, inferred types.   

Any files or preferably directories refactored with explicit (but careful) conversions to proper type declarations would make for a great PR.

**Comment by kcassam** [comment]
strictiness does not force you to type hint everything.
It will only throw "Uncaught TypeError" when there is a type mismatch.

So you should correct Uncaught TypeError when you find one.

You can use phpstan to enforce type hinting : https://phpstan.org/

**Comment by PThorpe92** [comment]
Yeah I noticed this, and even adding `strict_types` with the script to every file, I noticed I had to correct a couple "Uncaught type error"s. I figured it didn't enforce it project wide, which is why we were able to just add it early, despite not having complete type hinting yet.

To add it all at once, would mean adding type hints in essentially one PR/merge then? Is there a way to add this on a per-file basis? I definitely wish we would have enforced this from the start.

**Comment by kcassam** [comment]
Phpstan itself does not force you to do anything. When run, it only analyse the code statically and points defaults and suggest improvements

**Comment by PThorpe92** [comment]
Awesome, Thanks for adding this @kcassam 


### Update on Issue:

Currently the code-base is error free w/ CI check for up to `Level 2` of linting. Even getting from 0 -> 2 required fixing about 100+ errors (although many were just getting phpstan to understand the relations, etc) but I like the idea of slowly bringing the codebase up lint levels.

Incrementing the level in the `phpstan.neon` file and running `./vendor/bin/phpstan --memory-limit=1G` will give you a list of lints to work on. A file or directory with 1 lint level worth of fixes/doc comments/return types, etc would be a great PR.

Just be aware that many are simply phpstan not properly understanding relationships, etc. and to check their documentation for things like https://phpstan.org/user-guide/ignoring-errors where the errors need to be ignored.

**Comment by jtucholski** [comment]
@PThorpe92 We can close this, right? It was opened against the prior tech stack.
