### ISSUE TITLE
some classes do not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by kcassam** [UnlockedLabs/UnlockEdv2#192]
**Describe the bug**
when running `composer install` : 

```
Generating optimized autoload files
Class Tests\Feature\UserCourseActivityJob located in ./tests/Feature/UserCourseActivityJobTest.php does not comply with psr-4 autoloading standard. Skipping.
Class Tests\Feature\CanvasIntegrationTests located in ./tests/Feature/CanvasIntegrationTest.php does not comply with psr-4 autoloading standard. Skipping.
Class App\Entities\IdentityEntity located in ./app/Entities/UserEntity.php does not comply with psr-4 autoloading standard. Skipping.
```

**To Reproduce**
- clone the project
- run `composer install`

**Expected behavior**
All classes should comply with psr-4 autoloading standard

**Screenshots**
<img width="962" alt="Capture d’écran 2024-04-13 à 11 38 15" src="https://github.com/UnlockedLabs/UnlockEdv2/assets/150823/b6f39656-c142-4e68-bf02-b9abbf13d9c2">

**Comment by PThorpe92** [comment]
Yeah thanks for reporting this!

Saw this one in the initial loading of phpstan locally. Fixed these and a bunch more issues and got the lint level up to 2 from 0 in #196  :D 

Unfortunately a good amt of the work fixing a lot of the other lints was more just getting Phpstan to recognize relationships and methods/fields, but with the amount of actual issues that it found, it was worth fighting with it for a day.
