### ISSUE TITLE
All users should be able to login with a username and password

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#199]
Laravel’s default is to use an email to sign in, but most of our students will not have an email address and will not have outside internet access. We will need to make the needed modifications to the model, controllers, and UI to make the switch to using usernames instead of emails for logins.

- [ ] Update the login form in the UI
- [x] Update the login controller

**Comment by PThorpe92** [comment]
![image](https://github.com/UnlockedLabs/UnlockEdv2/assets/121899304/ddb737d9-5c3b-4a49-82e7-abc843db1a02)

UI is currently using username. Back-end/auth has recently been changed to use username in place of email for the OIDC Claims, as this is how we will be logging into Kolibri. 
This is all set :+1:
