### ISSUE TITLE
Connect to database to get programs (course catalog page)

### ISSUE THREAD

**Issue by calisio** [UnlockedLabs/UnlockEdv2#247]
- Create an api that returns all courses the may enroll in

**Comment by PThorpe92** [comment]
`/api/users/{id}/catalogue` is now available with the `tags` query string, which you can use for the tags in the UI
e.g.
`?tags=grades&tags=open_enrollment` and that will return only results matching the outcome types and the program type.

Also the endpoint  `PUT /api/programs/{id}/save` will either Save or Unsave the program from the users favorites, and those results are available on the dashboard endpoint.
