### ISSUE TITLE
Add password requirements to UI

### ISSUE THREAD

**Issue by calisio** [UnlockedLabs/UnlockEdv2#272]
We need to add password requirements to the password reset UI. There is no design as of now, but we'd love for it to look something along these lines:
<img width="360" alt="Screenshot 2024-06-24 at 4 44 34 PM" src="https://github.com/UnlockedLabs/UnlockEdv2/assets/89868388/84f08e81-9ec4-4354-97ce-6eb1f38585a4">
As of now we only have two requirements: the password must be greater than 8 characters and contain at least 1 number (so you can ignore the first two lines on that example above).

Please use colors that are already included in the theme. Symbols are important in terms of accessibility, so please include those also (as in using a check mark and an x). Let me know if you have any follow up questions and/or if you'd like to pick this up.

**Comment by jtucholski** [comment]
@calisio Should the password requirements list be positioned below the Password or Confirm Password field?
