### ISSUE TITLE
BUG: Inform user that username cannot have certain characters

### ISSUE THREAD

**Issue by calisio** [UnlockedLabs/UnlockEdv2#334]
**Describe the bug**
If a user creates a username that is invalid because it includes certain characters (such as spaces), it accepts it and strips them in the backend. This should not be accepted, but instead should prompt the user to choose a new username without these characters.

**To Reproduce**
1. Go to the Users page.
2. Click on the "Add User" button
3. Type in a username that includes some spaces or any other invalid character (ie "carolina     alisio")
4. the user will successfully be added to the database under the username "carolinaalisio" - the backend strips invalid characters and saves them in the database as such.

**Expected behavior**
Rather than allowing the username to be accepted, we should prompt the user to input a valid username. this error should be set using react hook form's `setError` (see https://github.com/UnlockedLabs/UnlockEdv2/pull/316#issuecomment-2273805693 for more info on what this should look like).

**Screenshots**
Screenshots are attached in [this github comment](https://github.com/UnlockedLabs/UnlockEdv2/pull/316#issuecomment-2273805693).

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 126.0.6478.127

**Comment by techeclecticdesign** [comment]
Since this is similar to what I just did I will happily take this on, thanks.

**Comment by techeclecticdesign** [comment]
@PThorpe92 ,
Did you still want the other validation checks following up on #349?

**Comment by PThorpe92** [comment]
I actually think all of those were added in a very large, breaking change introducing refactor that we did recently.
