### ISSUE TITLE
Make Dark Mode Lighter, Closer to Gray Than Deep Saturated Green

### ISSUE THREAD

**Issue by calisio** [UnlockedLabs/UnlockEdv2#341]
Dark saturated green of UnlockEd's dark mode is too dark. Make it closer to gray

**Comment by calisio** [comment]
Can you specify which dark green this is? Is this referring to the background or all greens. Changing from green to another color should be fairly easy, but I just want to be clear on the expectations. Could screenshots with examples be included? @chrissantillan

**Comment by chrissantillan** [comment]
@calisio the expectations are unclear at this point, just that it (the background) was too saturated, not necessarily too dark. Once I have clarity I'll let you know.

**Comment by chrissantillan** [comment]
We may revisit this once we hire a UX designer in the future.
