### ISSUE TITLE
Complete queries in kolibri provider middleware

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#392]
Josh has done research on querying kolibri's database as described in the notion document.

This document outlines most of the relevant tables needed for these queries.

A sqlite database has been provided with some basic test data, which can be used to explore their schema, test and develop the two remaining queries:

```go
func (ks *KolibriService) ImportMilestones(coursePair map[string]interface{}, mapping []map[string]interface{}, db *gorm.DB, lastRun time.Time) error {
```
 a coursePair is a map with two k/v's: `course_id` and `external_course_id`
the mapping slice is an array of `user_id` + `external_user_id` 
These can be used to access the relevant ID's of the courses+users the data is being fetched for. 

Milestones are points of achievement for a student, and are represented by the following types: 
```go
	Enrollment           MilestoneType = "enrollment"
	QuizSubmission       MilestoneType = "quiz_submission"
	AssignmentSubmission MilestoneType = "assignment_submission"
	GradeReceived        MilestoneType = "grade_received"
	DiscussionPost       MilestoneType = "discussion_post"
```
And Activity is any user quantifiable interaction with a provider. 
```go
	CourseInteraction  ActivityType = "interaction" // watching video, clicking link, etc
	ContentInteraction ActivityType = "completion"  // completing submodule, video, etc
```
 
 and 
```go
func (ks *KolibriService) ImportActivityForCourse(courseIdPair map[string]interface{}, db *gorm.DB) error {
```

**Comment by carddev81** [comment]
Found an ID mismatch issue.  When a kolibri user is being created via the POST webservice call to kolibri, it returns a hash id w/out hyphens...whereas the source hash id is hyphenated.  So for example a user in provider_user_mappings=10aab22d07b583d5dfd3ab3a6d636686 and the associated one in kolibriauth_facilityuser=10aab22d-07b5-83d5-dfd3-ab3a6d636686.  This is causing a mismatch issue within the middleware.
