### ISSUE TITLE
BUG: Validating When Editing Admins

### ISSUE THREAD

**Issue by corypride** [UnlockedLabs/UnlockEdv2#420]
**Describe the bug**
Error message appears under the Username field stating that the "Name + Username must contain letters and numbers only"  after I added letters only to the Last Name field

**To Reproduce**
1. Go to 'Admins'
2. Click on 'the pencil to edit an admin'
3.  Click on 'the Last Name field to edit an admins name and add some letters'

**Expected behavior**
Admin's last name to be changed

**Screenshots**
![image](https://github.com/user-attachments/assets/e7b64abc-e7ec-447e-ba6e-1436d41a8f22)

**Desktop (please complete the following information):**
 - OS: [Manjaro]
 - Browser [Chromium]
 - Version [Version 129.0.6668.70 (Official Build) Arch Linux (64-bit)]

**Comment by jtucholski** [comment]
I wasn't able to reproduce this exact issue but when I picked the task the update user handler wasn't working correctly.
