### ISSUE TITLE
BUG: Horizontal Scrollbars Visible for Breadcrumbs when on smaller screens

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#426]
**Describe the bug**
There are horizontal scrollbars visible in the breadcrumbs at the top of the page when using the application as an admin. These are visible on a 

**To Reproduce**
1. Visit Provider Platforms as an Admin
2. Click on **Manage Users** for Canvas
3. Note the breadcrumb text at the top of the screen is wider than the container allows

**Expected behavior**
The container should accommodate the text in the breadcrumb and not show a horizontal scrollbar.

**Screenshots**
![image](https://github.com/user-attachments/assets/36ef79bd-6281-47d4-b02f-bb5ec69f56cc)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser Edge
 - Resolution 2256 x 1504 (no zoom)

**Additional context**
When I view this on my external monitor everything looks correct. This only happens when I view it on my laptop monitor.

**Comment by jtucholski** [comment]
Depends on #428

**Comment by calisio** [comment]
For some reason I can't reproduce this bug? I don't have Edge, but doesn't seem to appear on Chrome Version 129.0.6668.70 (Official Build) (arm64) or on Safari Version 17.5.
