### ISSUE TITLE
UX Design for Program Management

### ISSUE THREAD

**Issue by jtucholski** [UnlockedLabs/UnlockEdv2#461]
## Description:

We need high-level interactive mock-ups for the **Program Management** section of our product. These mock-ups will demonstrate the key user flows and screens, including program creation, editing, viewing, and deactivation from an end-user's perspective. The designs should showcase basic functionality with clickable elements, allowing for partial interactivity in Figma to help visualize the user experience.

### Acceptance Criteria:

- [x]  Interactive mock-ups for creating a new program.
- [x]  Screens for viewing and managing a list of programs (e.g., filtering, searching).
- [x]  Screens for editing program details (e.g., title, description, tags, facilities).
- [x]  UI for activating/deactivating programs.
- [ ]  Option to archive or delete programs, with confirmation modals.
- [x]  All mock-ups should be interactive in Figma, showing basic transitions between screens (e.g., clicking "Create Program" opens the program creation form).
- [x]  Mock-ups should consider different user roles (e.g., department-level coordinator vs. facility-specific coordinator).

### Design Considerations
- Ensure consistency with existing UnlockEd UI components and design language.
- The designs should consider scalability (e.g., how large lists of programs will be displayed).
- Accessibility should be taken into account (e.g., ensuring buttons and forms are usable for keyboard navigation and screen readers)

### Outstanding decisions to determine with Product
- [ ] Indicate what a required field (like name) would look like.
- [ ] Are there any specific constraints for program names, tags, or facility assignments (e.g., character limits)?
- [ ] Can we adopt similar workflows for department-wide programs and facility-specific programs?

**Comment by calisio** [comment]
I anticipate the UI for program management for a department-wide admin will be done by Friday, but the UI for an individual admin might not be done by Friday.
