### ISSUE TITLE
BUG: User should not be able to publish changes if link title OR link URL is empty

### ISSUE THREAD

**Issue by calisio** [UnlockedLabs/UnlockEdv2#466]
**Describe the bug**
A use is able to publish a collection that has an empty title or empty URL, which should not be possible.

**To Reproduce**
1. Go to Resource Management page on admin view 
2. Click on a collection to modify
3. Delete entire name or entire URL or both and click publish changes
4. See error - should not be able to successfully do this.

**Expected behavior**
A URL or title should not be able to be empty.

**Screenshots**

https://github.com/user-attachments/assets/ef1fdb88-55f6-4d1f-86ce-9214a250dfb6

**Desktop (please complete the following information):**
 - Mac OS Version 14.5
 - Browser Chrome Version 130.0.6723.70

**Comment by jtucholski** [comment]
Verified that this continues to exist. When _adding a new link_ to the collection validation prevents users from entering an empty title or URL, but the edit screen does not.

**Comment by jtucholski** [comment]
@MillerSenior Can you shelve your work for this (don't get rid of it)? I'm going to move this into the Backlog until some further discussions are had about Resource Management.
