### ISSUE TITLE
Bug: Light/dark mode switch not working

### ISSUE THREAD

**Issue by calisio** [UnlockedLabs/UnlockEdv2#50]
The light/dark mode switch under the user dropdown menu does not appear to work; it pauses between attempting to switch but no colors change. I am able to click on the switch and it successfully moves back and forth, but the page does not change color. I am using chrome browser on macOS 14.2.1.

**Comment by nokierae** [comment]
Thanks @calisio !

Just a note to whoever ends up fixing this: I think the plan will be to swap out the naive method we are using now to using something like https://github.com/saadeghi/theme-change which will allow us to default to what the operating system is set to (dark or light), save their choice in localstorage, and actually apply the choice in a way that works cross browser.

**Comment by chrissantillan** [comment]
The light/dark mode works on my Windows 11/Firefox browser, but only when I have my Firefox appearance settings set to dark mode. It doesn't work when it is set to Automatic

**Comment by nokierae** [comment]
@chrissantillan and @calisio . I merged in a new theme toggle that should work. Pull from main and let me know.

**Comment by chrissantillan** [comment]
It works! Thanks @nokierae! Before I close this @calisio should probably check it out on her setup.

**Comment by calisio** [comment]
Works on my setup too! Good to merge in @chrissantillan @nokierae
