### ISSUE TITLE
Resources sidebar should present the enabled Open Content Providers

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#512]
Currently Wikipedia and Kolibri are hard coded to be presented to the user on the Student Dashboard. We should be fetching the enabled open content providers and showing those.

**Comment by calisio** [comment]
I am not sure this ticket will be relevant anymore with the new dashboards that are coming (ie. a dashboard for level 1, level 2, and level 3).
