### ISSUE TITLE
Update Dashboard Names for Resident and Admin Views

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#556]
## **Description**

Currently, all the dashboards across the three Layers in UnlockEd are generically called "Dashboard," leading to confusion for both the development team and users. To improve clarity and user experience, the dashboards will be renamed based on their specific function and context for **Residents** and **Administrators**.

### **Current Names**:  
- All dashboards are simply labeled "Dashboard."  

### **Proposed Name Changes**:  

| **Layer**                  | **Resident Dashboard** | **Admin Dashboard**     |  
|----------------------------|------------------------|--------------------------|  
| **Layer 1: Knowledge Base** | Trending Content       | Knowledge Insights       |  
| **Layer 2: Connected Learning** | Learning Path         | Learning Insights         |  
| **Layer 3: Program Hub**      | Program Tracker        | Program Insights          |  

These names provide intuitive descriptions of each dashboard’s purpose and functionality, making them easier to understand and navigate.

### **Frontend Tasks**  
- [ ] Update the **Resident Dashboard names** across the product:  
  - Layer 1: Change "Dashboard" to **Trending Content**.  
  - Layer 2: Change "Dashboard" to **Learning Path**.  
  - Layer 3: Change "Dashboard" to **Program Tracker**.  
- [ ] Update the **Admin Dashboard names** across the product:  
  - Layer 1: Change "Dashboard" to **Knowledge Insights**.  
  - Layer 2: Change "Dashboard" to **Learning Insights**.  
  - Layer 3: Change "Dashboard" to **Program Insights**.  
- [ ] Ensure the new names are reflected in:  
  - Dashboard navigation titles.  
  - Page headers or titles displayed on the dashboards themselves.  
  - Breadcrumbs or any navigation aids referencing dashboards.
  - Page URLs

### **Backend Tasks**  
- [ ] Check for any backend references to "Dashboard" tied to Layer-specific logic.  
- [ ] Ensure any APIs or configurations referencing these dashboards reflect the new names if necessary.

## **Acceptance Criteria**

- **Frontend**:  
  - Resident and Admin Dashboards are renamed as per the table above.  
  - The new names are displayed consistently in navigation, page headers, and any associated breadcrumbs.  
  - ~~All dashboard names are responsive and styled appropriately for different devices (desktop, tablet, mobile).~~  

## **Outstanding Questions**  
1. Are there any analytics or metrics tied to the current "Dashboard" naming that need to be adjusted or migrated?  
2. Should the name changes be reflected in external documentation or user-facing materials (e.g., guides, FAQs)?  
3. Are there tooltips referring to the generic "Dashboard" that now need to be updated?

**Comment by jtucholski** [comment]
@chrissantillan This bullet point under FrontEnd doesn't seem related to the overall task.

> All dashboard names are responsive and styled appropriately for different devices (desktop, tablet, mobile).

Can we remove it or write it up as a separate issue and indicate where there are issues?

**Comment by chrissantillan** [comment]
@jtucholski Yes we can remove it.

**Comment by jtucholski** [comment]
I hadn't seen that it said "names." My brain blocked that part out and replaced it with "All dashboards"

**Comment by jtucholski** [comment]
This and #563 should probably be done together.

**Comment by calisio** [comment]
closed with #536
