### ISSUE TITLE
BUG: Popular Knowledge Center Content contains empty list items

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#557]
**Describe the bug**
With Layer 1--Knowledge Base turned on (only), when I log on as a Resident the Popular Knowledge-Center Content section contains blank list items.

**To Reproduce**
1. Have Layer 1 turned on only (from the admin side)
2. Log into UnlockEd as a resident
3. See error (notice the two blank list items below "Lua.org":
![image](https://github.com/user-attachments/assets/8f32e8be-80c3-44df-afa8-087a74a88fbc)

**Expected behavior**
No blank list items should appear in the Popular Knowledge Center Content section

**Comment by jtucholski** [comment]
@chrissantillan Do you know how to reproduce this? This screenshot is from our staging environment (as a resident). 

![Image](https://github.com/user-attachments/assets/cede1da4-0107-40e2-8520-f4fbc52c1f44)
