### ISSUE TITLE
BUG: Profile Popout Disappears After Selecting Layer

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#562]
**Describe the bug**
As I was checking/unchecking the different layers in the profile popout, sometimes the popout would disappear, forcing me to click on the profile to get to the popout again. It does not happen all the time (see video below).

**To Reproduce**
1. Log into UnlockEd as SuperAdmin
2. Click on profile in lower left-hand corner of screen.
3. Click on/off different checkboxes.

**Expected behavior**
The popout should remain visible until user clicks in an area outside of the popout

**Screenshots**

https://github.com/user-attachments/assets/e5d7a18b-80c9-4207-811d-d1d3627e1dba

**Comment by jtucholski** [comment]
It seems to happen when unchecking the different features.

**Comment by CK-7vn** [comment]
I believe this behavior has been fixed. I talked with Preston, and checked it on staging. It's not happening anymore. Chris or Josh would you be able to double check this and see if it's still happening?

**Comment by jtucholski** [comment]
Closing this, I'm not seeing any more on development or in staging.
