### ISSUE TITLE
UI Updates: Rearrange Links in Left-hand Sidebar

### ISSUE THREAD

**Issue by chrissantillan** [UnlockedLabs/UnlockEdv2#563]
**Describe the bug**
This isn't so much of a bug as a fix. Rearrange the left-hand sidebar links as shown below:

1. Knowledge Base (Layer 1) activated only:

![Image](https://github.com/user-attachments/assets/8b39d147-762c-4012-a5e7-6a6c03897307)

2. Connected Learning (Layer 2) activated only:

![Image](https://github.com/user-attachments/assets/e8d54d4e-09f1-43ee-b6d7-68992a352ce1)

3. Knowledge Base AND Connected Learning activated together:

![KB_CLSidebarNav(1)](https://github.com/user-attachments/assets/374d81dc-ec9b-48b9-89da-585d43131bca)

**Comment by jtucholski** [comment]
@chrissantillan Is this the correct picture for Layer 2? 

Additionally, Operational Insights is grouped with Students, Admins, and Facilities in the Layer 1 image but under the Layer 1 AND Layer 2 image, it is grouped with the other Insights-related Dashboards. Is that correct?

**Comment by jtucholski** [comment]
This work depends or is directly aligned with #509

**Comment by chrissantillan** [comment]
@jtucholski made the corrections to the images
